### ISSUE TITLE
Cash Damage blink

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#1]
The cash damage plugin causes humans and zombies to constantly blink throughout the round. It stops for a few seconds randomly but its pretty unplayable.

**Comment by darkerz7** [comment]
> The cash damage plugin causes humans and zombies to constantly blink throughout the round. It stops for a few seconds randomly but its pretty unplayable.

This plugin was developed when cs go had no problems with transparency. I am thinking of removing this plugin
