### ISSUE TITLE
Music clientprefs issue

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#10]
Hey, there's an issue where music is auto disabled for clients, clientprefs is buggy only with this plugin.

**Comment by asphyxious** [comment]
Ah my bad, seems like they did !stopmusic which stopped their music, but !startmusic doesn't seem to enable music in clientprefs, only temporaraily stays for the map. Could you fix that?

**Comment by darkerz7** [comment]
Fixed
