### ISSUE TITLE
Entwatch minor issue

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#11]
Hey , for some reason entwatch NEVER works on first round, have to wait for it to go to second round.
I have a mp_warmuptime 90 that we use use and weirdly entwatch does usually work in warmuptime but never first round.

**Comment by darkerz7** [comment]
maybe fixed, need tests

**Comment by asphyxious** [comment]
It is. Could you possibly add a cvar to change what channel entwatch hud uses ? On some maps it blinks because map chat uses same channel, so I can use that cvar and set the channel different for that map with the cvar, would be really helpful.

**Comment by darkerz7** [comment]
Added new CVAR: entwatch_hud_channel <0/5>
