### ISSUE TITLE
Entwatch glow option

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#13]
Hey, could you add a cvar to disable entwatch glow through walls BEFORE items have been picked up? It results in a lot of noobs picking up items. The glow can be there but if you see all items through walls before they are picked up it ruins it a bit

**Comment by darkerz7** [comment]
Added new CVAR:
-entwatch_glow_spawn <0/1> - Enable/Disable Glow after Spawn Item
-entwatch_glow_spawn_type <0-3> - Type Glow after Spawn Item 0-Default(through walls), 1-Shimmer (doesn't glow through walls), 2-Outline (doesn't glow through walls), 3-Outline Pulse (doesn't glow through walls)
-entwatch_glow_drop_type <0-3> - Type Glow after Drop Item, types are similar CVAR: entwatch_glow_spawn_type
