### ISSUE TITLE
music plugin issue

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#14]
Hey, seems like the !music plugin doesn't work on a few maps [Such as roof adventure / crazy escape etc] and on a lot of MG maps as well. Is there any fix for this?

**Comment by darkerz7** [comment]
maybe the sound doesn't come from entity ambient_generic but from soundscape

**Comment by darkerz7** [comment]
hmmmm... the author for some reason adds to the title of the track *
![image](https://user-images.githubusercontent.com/25752428/78380501-675bf480-75ed-11ea-9d6f-8169a4650be9.png)

**Comment by darkerz7** [comment]
seems to have fixed

**Comment by asphyxious** [comment]
Thats good, it still has the weird issue of it completely bootsing the noisy in some maps like castelvania and roof adventure [while obss fight], and its really cancerous. Not sure if this can be fixed
