### ISSUE TITLE
Top defenders still blinking

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#15]
Hey, top defenders is still causing all player models [human and zm] to constantly blink . Not sure what is causing this

**Comment by darkerz7** [comment]
try setting another rendermode in the config(Perk_RenderMode), but I tested with ZR Franug edition and did not observe any problems with blinking with 64 players. such a problem occurs when the authors of the maps themselves rendermode, e.g. ze_journey

**Comment by asphyxious** [comment]
Oh, yeah it happens on most maps. Is it all the icons that use rendermode? Could it be possible to have icons that dont use rendermode? Or any other option that might not have these

**Comment by darkerz7** [comment]
I do not use rendermode on player skins. the only thing where rendermode is used is perks, which in turn can be configured in the config
