### ISSUE TITLE
Music and entwatch changes

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#16]
Hey, for music plugin is it possible to add an option to reduce map sounds as well instead of just ambient? Like wanderers etc has really loud item noises.  Would be awesome to have an option to reduce those, I've seen it on servers like pse

And for entwatch , it seems like only root flag can use sm_status <name> , and that means other admins cannot check status of other players, only your own. Could you add a cvar to set which flag can use or just let everyone use this to see others status?

**Comment by darkerz7** [comment]
music plugin does not capture sounds shorter than 10 seconds(CVAR sm_stopmusic_music_length). EW used ADMFLAG_BAN flag to sm_status

**Comment by asphyxious** [comment]
Will it cause major issues if i put the length to 1 second?

**Comment by darkerz7** [comment]
sounds from entity ambient_generic, whose length will be more than 1 second, will be considered by the plugin
