### ISSUE TITLE
What does antistack damage do?

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#17]
Hey, I was wondering what does ANTI Stack damage plugin do?

**Comment by darkerz7** [comment]
In cs go there is an unpleasant bug, if the trigger_hurt has a parent and it does not imply instant killing of the player, then sometimes it happens that for 1 touch of the trigger the server counts 4 or more touches. for example, it was understood that in 0.5 seconds 25 damage would be done, but 100 or more

**Comment by darkerz7** [comment]
Mappers usually fix this - either turn off the trigger for 0.5 seconds or set a filter blocking the corresponding type of damage

**Comment by darkerz7** [comment]
This bug appears only on community servers, in a single game everything works as it should

**Comment by darkerz7** [comment]
This plugin only captures a trigger_hurt. Stack damage may still be at the door, but it cannot be fixed. although it can be fixed with a bunch trigger_hurt+func_door using a stripper
