### ISSUE TITLE
Map music double play

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#2]
Hey, the music overlaps on a lot of songs. 
For example mako 

Two songs will play simultaneously during boss fight, which gets very loud and annoying,

Any fix for this??

**Comment by asphyxious** [comment]
Also only with your plugin, on some maps like castlevania / roof adventure etc, there's sometimes loud noises like boss noises that get super bass boosted and loud.

**Comment by darkerz7** [comment]
I fixed double music. Loud sounds may be due to the fact that standard sound scripts are used(not mp3/wav file). These sounds may also be too short, try changing the value of the CVAR sm_stopmusic_music_length (How long required length for it will be music files.)

**Comment by asphyxious** [comment]
Hmm I tried it with other music plugins like krxnrl's, it didn't seem to break though. I'll test the latest version of yours and check
