### ISSUE TITLE
entwatch issue

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#20]
Hey, players cant seem to use items unless they spam e or jump/spam e

Im guessing it might be due to the disabling of epicking. Is there a way to fix?

**Comment by darkerz7** [comment]
Most entwatch also do not allow the use of the item in the crowd. Need to directly hover over the button. I tried to add use to entwatch regardless of the situation - need uncomment **#define ENTWATCH_USE_PRIORITY** and recompile. But double triggering possible. For example, 2 buttons on the item or along with the item you press the button on the map

**Comment by asphyxious** [comment]
yeah maybe add a cvar for that because its annoying my players as they have to keep spamming

**Comment by darkerz7** [comment]
specifically what case

**Comment by asphyxious** [comment]
Okay with current version, players can epick, and tends to happen is all the noob epickers hold e, and tend to use item right after picking it up. Is there some middle way where players can't epick, and don't have to spam use items.

**Comment by darkerz7** [comment]
that is, to make a slight delay after selecting an item? for example, a person picks up an item and cannot use it for the first 3 seconds

**Comment by asphyxious** [comment]
maybe 2 seconds , yeah, that will be good.

**Comment by darkerz7** [comment]
Added
