### ISSUE TITLE
Entwatch issue still exists

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#21]
Hey, i like the cooldown addition, that works.

There is still an issue where players HAVE  to jump or spam e multiple times to use item. Its very annoying for clutch situations. Is this the button plugin by you or entwatch?

Also, with the latest addition, entwatch_mode_teamonly 1 doesn't work, we can see both human and zm items on EW [Tested on ridorana, ill test on more maps soon]

**Comment by darkerz7** [comment]
To use items in the crowd uncomment the line #define ENTWATCH_USE_PRIORITY and recompile plugin(this is line 27). About CVAR I fixed adaptation, but admins or spectators see all items. In order that admins did not see items use CVAR entwatch_admins_see

**Comment by asphyxious** [comment]
Normal players can see it as well. I'll try with cvar and disable it i guess.

**Comment by asphyxious** [comment]
Also , could you add an option to only see human items even as a zombie? We don't really care about zm items, human items are the most important.

**Comment by darkerz7** [comment]
Set CVAR entwatch_mode_teamonly 0 and entwatch_admins_see 0 (The second cvar, so that the server loads a little less, if you use the first). Priority Humans Items.

**Comment by asphyxious** [comment]
It's still pretty messy, with entwatch_mode_teamonly 0 I can see both human and zm items.
I have an idea, a player suggested this, can you make it so player can individually choose if they want to see only team or both team items ? [Should be team only by default]

Could be a command like !fullentwatch or !fullhud

**Comment by darkerz7** [comment]
Do you use the latest version of entwatch? And admins should see all the items to more control the gameplay(ADMFLAG_KICK or ADMFLAG_ROOT).

**Comment by darkerz7** [comment]
entwatch_mode_teamonly toggles the visibility of opposing team items for regular players. entwatch_admins_see toggles the visibility of opposing team items for admins.

**Comment by asphyxious** [comment]
Hey I realised the issue. I think its the buttonwatcher plugin. It doesn't let player press e when they are in stack [Cant press buttons either on maps if they are stacked]

Please fix this, causing a lot of issues

**Comment by asphyxious** [comment]
My bad, after more testing it seems like this plugin causes it: https://github.com/KoreanDude/csgo-ze-plugins/tree/master/Penetration%20Bullets/scripting [Collisionhook]

Do you use it by any chance? When zr_collison_enable is 0 [to reduce lag], humans cannot press e or item or buttons when they are in a stack.

**Comment by darkerz7** [comment]
As far as I remember this causes some problems. Therefore, on some servers it was abandoned
