### ISSUE TITLE
There's an issue with music

### ISSUE THREAD

**Issue by zeddy1234** [darkerz7/CSGO-Plugins#22]
Hey, Memories told me I should report an issue here. 
So there's an issue with the music plugin [we only checked on surf_dark_Fantasy_v2_go2]

The map music keeps switching off with every teleporter. Players must change music volume with !music. For example I have 50 vol, when i go through teleporter music will automatically trigger off. To enable it, I need to use !music 45 or !music 80 etc, keep changing volume every teleport to make it work.

**Comment by darkerz7** [comment]
Maybe the plugin mapmusic conflicts with other plugins. I checked everything is fine with the music
