### ISSUE TITLE
Add physbox to EW?

### ISSUE THREAD

**Issue by zeddy1234** [darkerz7/CSGO-Plugins#23]
https://github.com/gflclan-cs-go-ze/ZE-Configs/blob/master/entwatch/ze_lotr_isengard_csgo1.cfg

Hey, GFL recently started updating their entwach configs with a new PHYSBOX config

Could you incorporate it in your plugin?

"physbox"           "" //OPTIONAL: "true" if this item is a physbox so it would allow bullets/knife to shoot/knife through. If it's false, dont bother adding this line.

**Comment by darkerz7** [comment]
I met similar, on some maps there is protection against pick up of an item on E, For example cosmo. With my EW this physbox is not needed. It happens that because of it it is impossible to pick up an item. This is fixed by removing the physbox with a stripper

**Comment by darkerz7** [comment]
and maybe I understood what you mean ... well, I don’t know if this is necessary

**Comment by darkerz7** [comment]
I do not think that this option will be useful
