### ISSUE TITLE
Entwatch name / reason

### ISSUE THREAD

**Issue by zeddy1234** [darkerz7/CSGO-Plugins#24]
Hey, so for ebans, !status doesn't show who banned player or what reason. Could you add a feature like that? Because players keep asking for e-unban but we dont know which admin banned or why.

**Comment by darkerz7** [comment]
You can see which admin banned the player. sm_admin->entWatch Commands->List Banned Clients->{UserName}
![20200516161314_1](https://user-images.githubusercontent.com/25752428/82118386-84f5af80-9790-11ea-802f-0c081dbfbb71.jpg)

**Comment by zeddy1234** [comment]
Yes true, but it would be nice if admins can use reason [So there's no drama later]

Like !eban zeddy 60 "Trolling earth"

**Comment by darkerz7** [comment]
posted a new test plugin that has this feature
