### ISSUE TITLE
Music plugin issue

### ISSUE THREAD

**Issue by zeddy1234** [darkerz7/CSGO-Plugins#25]
Hey, memories told me I should ask you if there's a possibility to fix super loud earrape music on typical luffaren maps and other maps for CSGO.

It's kinda annoying and I've seen other servers fix this issue. Is that possible?

**Comment by darkerz7** [comment]
Reworked version https://github.com/darkerz7/CSGO-Plugins/tree/master/MapMusic_DZ%20Dhook%20SoundLib2
