### ISSUE TITLE
Entwatch bugs

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#3]
Hey, entwatch plugin bugs with a lot of maps.

For example, maps like minas tirith , half the barricades dont work

Maps like wanderers v5, oath doesn't work

It works with correct entwatch configs with other entwatch plugins, just not this one.

**Comment by darkerz7** [comment]
Possibly fixed. You can not give out an item that is not yet spawned on the map. There is a small bug when the author of the map kills pistols and spawns new ones. The give menu displays both options

**Comment by asphyxious** [comment]
Not using give items. It's default items.

**Comment by darkerz7** [comment]
well maybe it's fixed too

**Comment by asphyxious** [comment]
Doesn't show gun glow below players [below the playerskin] anymore.

**Comment by darkerz7** [comment]
the glow is done as follows - next to the weapon the prop_dynamic_glow is spawned and it is the glow that gives it. if the player picks up a weapon, then the glow should turn off. if the player disconnects / dies, then the glow turns on again

**Comment by darkerz7** [comment]
or did you mean that the player did not pick up the weapon, but it does not glow. it is possible that when a player approaches the skin, he teleports him to the room where this weapon is located.

**Comment by darkerz7** [comment]
if there are any problems - write the name of map

**Comment by asphyxious** [comment]
Ah, because in previous version there used to be a pistol/knife under the player [glowing in the ground] if that makes any sense. And that used to show item user easily.
