### ISSUE TITLE
buttonwatcher problem

### ISSUE THREAD

**Issue by rcon420** [darkerz7/CSGO-Plugins#35]
[SM] Unable to load plugin "buttonwatcher.smx": Could not find required plugin "entwatch_csgo_dz.smx"
I use new Entwatch plugin working fine. 

Can you help me out? 

i tried to update button watch but without success.

**Comment by darkerz7** [comment]
in version 3.DZ.x the include has changed. need to change in lines #6 #include &#60;entWatch>   ->   #include &#60;EntWatch>
#567 and #578 if(entWatch_IsSpecialItem(iButton)) return Plugin_Continue;   ->   if(EntWatch_IsSpecialItem(iButton)) return Plugin_Continue;
#934 if(entWatch_IsSpecialItem(caller)) return Plugin_Continue;   ->   if(EntWatch_IsSpecialItem(caller)) return Plugin_Continue;

**Comment by rcon420** [comment]
Thank you for pointing out  silly mistake What I made forgot to update Include name :)°
Plugin works!
