### ISSUE TITLE
Entwatch glow player

### ISSUE THREAD

**Issue by ByKyTa** [darkerz7/CSGO-Plugins#36]
Can you add glow player?
![image](https://user-images.githubusercontent.com/33537916/93658553-bf38cb80-fa66-11ea-8a82-0e6ef7018b22.png)

**Comment by darkerz7** [comment]
There are certain problems with this, so the glow of the players is not added. For example, this is the addition of an extra entity->edict(prop_dynamic_glow), problems if the skin is taken after the selection of an item and other...
