### ISSUE TITLE
Entwatch glowing equipped weapon entity.

### ISSUE THREAD

**Issue by nuclearsilo583** [darkerz7/CSGO-Plugins#38]
Hi, is there any way that once the items are picked up. it still continue glowing the equipped weapon on player models. 
example: if weapon item is weapon_elite, if player dont  using secondary weapon the item still glowing on their leg. If item is weapon_knife (for zombie) the knife of the carrier still glowing
Sorry for my bad english

**Comment by darkerz7** [comment]
maybe some plugin conflicts with EW. try running on a clean server

**Comment by nuclearsilo583** [comment]
sorry but maybe you're misunderstanding, i'm requesting for the weapon item still glowing when player pick it up. this is  what i saying
![glow](https://user-images.githubusercontent.com/58926275/107126201-f3f7d300-68e0-11eb-95d2-191324ad02e3.png)

**Comment by darkerz7** [comment]
the glow of the item should be turned off when the item is picked up. something on the server conflicts with this. other servers do not seem to experience this problem

**Comment by nuclearsilo583** [comment]
Oh, i mean ye the original ew of your dont have this since the glow turned off when player pick up. But can you add feature that it still glowing like the picture. Sometime player pick up an item and door hugging. I want to pinpoint what item they are holding by color configured  quickly without watching the hud and name. Same as picture the weapon still glowing and can be configured with different color. Thank you. 
If you dont understand what i mean. Please have a look at this video https://youtu.be/wWNn0SVih7A at 13:40. There's a player holding an item and his gun weapon (weapon_elite is an entity item on that map) glowing on his leg
P/s: Im using old entwatch not DZ version

**Comment by darkerz7** [comment]
I do not support the old version. perhaps by looking for the 'DisableGlow' function(EntWatch Old) and commenting it out, you will achieve the desired result. if I am not mistaken this is in line #1285

**Comment by NJOOSHY** [comment]
oh btw darkerz when i disabled function of disabled glow , its just buggy the guns spawn underneath you while glowing , instead of glowing your equipped guns
