### ISSUE TITLE
Entwatch DZ error on player rebuy items slot

### ISSUE THREAD

**Issue by nuclearsilo583** [darkerz7/CSGO-Plugins#39]
Hi, i used your entwatch dz and find error. I use [this rebuy](https://github.com/KoreanDude/csgo-ze-plugins/blob/master/Buy%20Commands/sm_buycommands.sp) plugin.
When ever i have item (weapon_elite) and rebuy any pistol, yes the item got toss out but no glow, hud still display me and the items become in valid edit(no owner or owner is invalid).
I cant use etransfer by command (also in admin menu) but error log say the item is invalid.
I use old entwatch and have no issue about this. 
Could you please fix . thank you

**Comment by darkerz7** [comment]
change all 'SDKHooks_DropWeapon(client, weapon);' to 'CS_DropWeapon(client, weapon, true);'

**Comment by nuclearsilo583** [comment]
fixed. Thanks
