### ISSUE TITLE
Music stops on death

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#4]
Hey, not sure if there's anything the plugin can do but music stops whenever you die. Is there any way to work around it?

**Comment by darkerz7** [comment]
strange, my music does not interrupt when I die(kill command) or go to the spectators. noticed a small bug when watching a player, 3D sound is played depending on the position of the camera. if you use a free camera then everything is fine

**Comment by darkerz7** [comment]
Fixed by replacing SNDLEVEL_NORMAL with SNDLEVEL_NONE

**Comment by asphyxious** [comment]
That worked, cheers 👍
