### ISSUE TITLE
Need adaptation

### ISSUE THREAD

**Issue by Truyn** [darkerz7/CSGO-Plugins#40]
is it possible to add support to github.com/darkerz7/CSGO-Plugins/tree/master/EntWatch_DZ
 github.com/darkerz7/CSGO-Plugins/tree/master/buttonwatcher

**Comment by darkerz7** [comment]
change in https://github.com/darkerz7/CSGO-Plugins/blob/master/buttonwatcher/scripting/buttonwatcher.sp **entWatch -> EntWatch**, and use include from https://github.com/darkerz7/CSGO-Plugins/tree/master/EntWatch_DZ/addons/sourcemod/scripting/include/EntWatch.inc

**Comment by Truyn** [comment]
thx bro
