### ISSUE TITLE
Entwatch DZ trigger issue + glow equip

### ISSUE THREAD

**Issue by NJOOSHY** [darkerz7/CSGO-Plugins#41]
1. Item cannot be activated if teammates block the site, already uncomment use priority to fix but the issue still occurs 

2. After disabling the function of disabling glow after players pick up guns, the guns are duplicated underneath the player and glow under your feet  I think it needs a custom-made glowing player equip state?

Sorry for bring two topics but i wanted to make it one thread :)

**Comment by NJOOSHY** [comment]
Functions:
-Allows you to use the item in the crowd
 but still can't use on crowd, its really frustating with high amout of player stacking in one place like (elevator ) and server is crowded , can't find a way to fix this issue yet

**Comment by notkoen** [comment]
> Functions: -Allows you to use the item in the crowd but still can't use on crowd, its really frustating with high amout of player stacking in one place like (elevator ) and server is crowded , can't find a way to fix this issue yet

Have you checked to make sure you have compiled with the right modules and checked if you set the cvar to 1? I know it's a bit redundant to ask this but we use the same plugin on Zeddy and never had any issues using items even when stacked.

**Comment by NJOOSHY** [comment]
> > Functions: -Allows you to use the item in the crowd but still can't use on crowd, its really frustating with high amout of player stacking in one place like (elevator ) and server is crowded , can't find a way to fix this issue yet
> 
> Have you checked to make sure you have compiled with the right modules and checked if you set the cvar to 1? I know it's a bit redundant to ask this but we use the same plugin on Zeddy and never had any issues using items even when stacked.

im no longer use_priority module , and uncomment everything related already , means cvar does not exsist anymore somewhow the issue still there

**Comment by notkoen** [comment]
> im no longer use_priority module , and uncomment everything related already , means cvar does not exsist anymore somewhow the issue still there

Huh? So you are not using the `module_use_priority.inc` but uncommented everything? Im a bit confused here. When I compiled the EntWatch plugin, I had included the module, so we don't have that issue.

**Comment by NJOOSHY** [comment]
> 

yeah im not using that  module , for testing bcs darkers say its the main caused , tried to disable  it using cvar also not work

**Comment by NJOOSHY** [comment]
compiled with user priority module and without still the same issue

**Comment by notkoen** [comment]
You can try using [this plugin](https://github.com/AgentWesker/zr_buttontracer) from Wesker. Allows you to press buttons through the crowd
