### ISSUE TITLE
A possible memory leak problem(To your Entwatch plugin)

### ISSUE THREAD

**Issue by tenshi97** [darkerz7/CSGO-Plugins#42]
According to my tests and statistics, there may be a problem with arraylist,that is:if you only use the method .clear(), it will not clear the data from memory, which will cause entwatch plugin's memory use expanding and finally causing memory leak. Maybe you should use Closehandle at every mapend and createarray at every mapstart

**Comment by darkerz7** [comment]
Fixed

**Comment by tenshi97** [comment]
there may be same problems with the music plugin
