### ISSUE TITLE
Zvol addition?

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#5]
Yo, is it possible to have a !zvol addition on music plugin? I've seen a few other servers have it. It helps reduce the audio of non music stuff like item sounds or other map sounds that r not affected with mapmusic.

**Comment by darkerz7** [comment]
initially this plugin was designed to work only with ambient_generic entities. to implement the functionality you proposed, you need to rewrite more than half of the plugin

**Comment by darkerz7** [comment]
but specifically about !zvolume or !zsound, here you need to edit the ZR
