### ISSUE TITLE
Unban menu, translations, hudetype code

### ISSUE THREAD

**Issue by Rushaway** [darkerz7/CSGO-Plugins#52]
- Add a menu for Unban Reason with translations
- Improving code for HudType
- Improving display of printed chat

See https://gitlab.com/counterstrikesource/sm-plugins/entwatch/-/commit/d0c1402e33114d48ce48b5b2e3b4aa6d9be9379e

**Comment by darkerz7** [comment]
not needed in csgo KeyHintText
colors are used for other purposes
when using a console command, there is no need to use pop-up menus
