### ISSUE TITLE
Separate each plugin into its own github repository

### ISSUE THREAD

**Issue by maximee-leroyy** [darkerz7/CSGO-Plugins#55]
Contribution would be easier if you could separate each plugin into a single git repository like this one for instance:
- https://github.com/srcdslab/sm-plugin-EntWatch

You could still keep this repository without any problem by using submodules to fix versions!

https://nide.gg developers will contribute to your repositories if you could do that and help you adding new features for csgo/css etc

@darkerz7

**Comment by maximee-leroyy** [comment]
cc @darkerz7

**Comment by darkerz7** [comment]
Moved to https://github.com/darkerz7/EntWatch_DZ

**Comment by maximee-leroyy** [comment]
thanks a lot!
