### ISSUE TITLE
HUD size too big

### ISSUE THREAD

**Issue by KvN069** [darkerz7/CSGO-Plugins#56]
Hello, I would like to ask how can we make the HUD size of EntWatch smaller? It is so big even on 1440p resolution.

Attached a picture.

![image](https://user-images.githubusercontent.com/20592607/199546877-a749c3da-c761-446c-8e6b-029b2d6474bd.png)

**Comment by darkerz7** [comment]
it's a csgo bug. you need to start the game with FullHD resolution(-w 1920 -h 1080 +exec autoexec.cfg) and autoexec.cfg (mat_setvideomode 2560 1440 0)
