### ISSUE TITLE
Block pickup e doesn't work, and top defender

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#6]
Hey, the BLOCK PICKUP e plugin doesn't work, players can simply pickup weapons with e.

Also, could you possibly add the top defender plugin back with a fixed edit? It was a really cool plugin, just that sometimes humans or zombies start blinking with it.

**Comment by darkerz7** [comment]
generally it’s better to insert the BLOCK PICKUP E directly into the Entwatch

**Comment by darkerz7** [comment]
built the BLOCK PICKUP E into Entwatch. Pistols can be picked up at some distance, but not with the E button. I wanted to make it impossible to throw out the item by pressing E, but there was a bug, the item's pistols were in my hands, but all the attached entities are on the ground

**Comment by asphyxious** [comment]
Seems to work somewhat. Could you make it possible to change color of entwatch hud from white?

**Comment by darkerz7** [comment]
Added sm_hudcolor command. Default values can be specified in the file cfg/sourcemod/entwatch/colors/<name_theme>.cfg

**Comment by darkerz7** [comment]
Added a reworked version of the top defenders perk plugin
