### ISSUE TITLE
Buttonwatcher issue

### ISSUE THREAD

**Issue by asphyxious** [darkerz7/CSGO-Plugins#9]
Hey, buttonwatcher has an issue. When players have items like belmont, it spams the "Has pressed button_belmont" etc in chat all the time. Could you make it so maybe it doesnt spam chat all the time? Happens on a lot of maps where they need to press e multiple times on an item.

**Comment by darkerz7** [comment]
For such cases there is a sm_buttons_view cvar that globally prohibits the display of pressed buttons. Or the client can write sm_buttons himself, so as not to see the pressed buttons. I prefer that every button pressed shows in the chat.

**Comment by darkerz7** [comment]
You can of course think of a list of buttons forbidden to be shown, for example by a hammerid. but again, this is an extra load on the server and database. Well, you will need to manually register them for each map

**Comment by asphyxious** [comment]
Hmm, that's weird because the oldschool buttonwatcher plugin only showed it like once every few seconds. https://github.com/Franc1sco/Button-Watcher

Could you possibly make it like that? It shows it the first time someone spams e and doesn't show it for a few seconds after.

**Comment by darkerz7** [comment]
Added CVAR sm_buttons_timer <0.0/10.0>
